### ISSUE TITLE
Add support for tagging tanzakus

### ISSUE THREAD

**Issue by cedricium** [cedricium/tanabata-tree#20]
This issue tracks the feature for adding support for tagging tanzakus. 

When implemented, tags will look similar to this:

![screen shot 2017-11-09 at 12 47 34 pm](https://user-images.githubusercontent.com/16343560/32629113-f57e0e96-c54c-11e7-8b36-66e7d09c67e0.png)

**High-Level Outline:**
- tags will be clickable in order to allow for filtering of that specific tag text
- limit 3 (three) tags per tanzaku
- when tags added or modified, PUT request is sent to update tanzaku's (using tanzakus `id`)
- use Bulma class 'tag is-light', with the following modifications:
```css
.tag.is-light {
  background-color: #ecf0f1;   /* litte darker and easier to see */
  color: #363636;
}
```
